version: 0.2

phases:
  install:
    commands:
      - echo Installing Node dependencies...
      - npm install
  build:
    commands:
      - echo Building the React Vite app...
      - npm run build
  post_build:
    commands:
      - echo Moving build to root folder
      - mkdir -p dist/scripts
      - cp -r scripts dist/
      - cp appspec.yml dist/

artifacts:
  files:
    - "**/*"
  base-directory: dist
