version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React Vite app...
      - npm run build

  post_build:
    commands:
      - echo Preparing artifact...
      - mkdir -p deploy-artifact
      - cp -r dist/* deploy-artifact/       # Copy built files
      - cp appspec.yml deploy-artifact/     # Copy appspec.yml
      - cp -r scripts deploy-artifact/      # Copy lifecycle scripts

artifacts:
  files:
    - '**/*'
  base-directory: deploy-artifact
